/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Priority = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
});
export const TaskStatus = IDL.Variant({
  'Done' : IDL.Null,
  'ToDo' : IDL.Null,
  'InProgress' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Opt(IDL.Int),
  'status' : TaskStatus,
  'title' : IDL.Text,
  'endTime' : IDL.Opt(IDL.Int),
  'conference' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'description' : IDL.Opt(IDL.Text),
  'deadline' : IDL.Opt(IDL.Nat),
  'priority' : Priority,
  'assignees' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const TeamMember = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'claimedBy' : IDL.Opt(IDL.Principal),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTeamMember' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimTeamMember' : IDL.Func([IDL.Nat], [], []),
  'createTask' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Int),
        Priority,
        IDL.Text,
      ],
      [Task],
      [],
    ),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getTasksByAssignee' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'removeTeamMember' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateTask' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Int),
        Priority,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateTaskStatus' : IDL.Func([IDL.Nat, TaskStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Priority = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
  });
  const TaskStatus = IDL.Variant({
    'Done' : IDL.Null,
    'ToDo' : IDL.Null,
    'InProgress' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Opt(IDL.Int),
    'status' : TaskStatus,
    'title' : IDL.Text,
    'endTime' : IDL.Opt(IDL.Int),
    'conference' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'description' : IDL.Opt(IDL.Text),
    'deadline' : IDL.Opt(IDL.Nat),
    'priority' : Priority,
    'assignees' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const TeamMember = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'claimedBy' : IDL.Opt(IDL.Principal),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTeamMember' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimTeamMember' : IDL.Func([IDL.Nat], [], []),
    'createTask' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Int),
          Priority,
          IDL.Text,
        ],
        [Task],
        [],
      ),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getTasksByAssignee' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'removeTeamMember' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateTask' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Int),
          Priority,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateTaskStatus' : IDL.Func([IDL.Nat, TaskStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };