/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Priority = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
});
export const Status = IDL.Variant({
  'CarryForward' : IDL.Null,
  'InProgress' : IDL.Null,
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'title' : IDL.Text,
  'assignedTo' : IDL.Text,
  'createdAt' : IDL.Int,
  'conferenceName' : IDL.Opt(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'deadline' : IDL.Int,
  'priority' : Priority,
});

export const idlService = IDL.Service({
  'addTeamMember' : IDL.Func([IDL.Text], [], []),
  'createTask' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Int,
        Priority,
      ],
      [],
      [],
    ),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getTasksByAssignee' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
  'getTeamMembers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'removeTeamMember' : IDL.Func([IDL.Text], [], []),
  'updateTaskStatus' : IDL.Func([IDL.Nat, Status], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Priority = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
  });
  const Status = IDL.Variant({
    'CarryForward' : IDL.Null,
    'InProgress' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'title' : IDL.Text,
    'assignedTo' : IDL.Text,
    'createdAt' : IDL.Int,
    'conferenceName' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'deadline' : IDL.Int,
    'priority' : Priority,
  });
  
  return IDL.Service({
    'addTeamMember' : IDL.Func([IDL.Text], [], []),
    'createTask' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Int,
          Priority,
        ],
        [],
        [],
      ),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getTasksByAssignee' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
    'getTeamMembers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'removeTeamMember' : IDL.Func([IDL.Text], [], []),
    'updateTaskStatus' : IDL.Func([IDL.Nat, Status], [], []),
  });
};

export const init = ({ IDL }) => { return []; };